version: "3.8"
services:
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass redis
    ports:
      - "127.0.0.1:6379:6379"
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "127.0.0.1:8001:8001"
    depends_on:
      - redis
