### create user stat
POST {{baseUrl}}/{{user_stats}}
Content-Type: application/json

{
  "id": "111e473f-6d90-4f2d-a9bc-2277eb78d56c",
  "user_id": "e2e6d5a3-843a-44a9-8881-114f117059e9",
  "name": "tickets.created",
  "value": 22.52
}

### create random user stat
POST {{baseUrl}}/{{user_stats}}
Content-Type: application/json

{
  "user_id": "e2e6d5a3-843a-44a9-8881-114f117059e9",
  "name": "tickets.created",
  "value": 22.52
}

### delete user stat
DELETE {{baseUrl}}/{{user_stats}}/111e473f-6d90-4f2d-a9bc-2277eb78d56c